### ISSUE TITLE
Heading component: missing variants

### ISSUE THREAD

**Issue by OliBridgman** [cultureamp/kaizen-design-system#1952]
### If it's a discussion, please start one [here](https://github.com/cultureamp/kaizen-design-system/discussions).

- [x] Before opening this issue, I've searched open and closed issues for a fix.

## Expected Behaviour

The typography documentation has a section for 'data': https://cultureamp.design/guidelines/typography/#data

While the tokens can be consumed, there is no component that encapsulates this.

Can we (should we?) add these variants to the Header component?

* data-large
* data-medium
* data-small
* data-unit-large
* data-unit-medium
* data-unit-small

Alternatively we make a Data component but that seems... A little overboard? Any use I've seen of these tokens is for heading-like DOM nodes.

## Actual Behaviour (please provide screenshots if it's a visual issue)
I'm not even sure if this is correct but something like:

`ANumber.scss`
```scss
@import "~@kaizen/design-tokens/sass/typography";
.container {
  display: flex;
  flex-direction: row;
  align-items: baseline;
}

.number {
  font-family: $typography-data-large-font-family;
  font-weight: $typography-data-large-font-weight;
  font-size: $typography-data-large-font-size;
  line-height: $typography-data-large-line-height;
  letter-spacing: $typography-data-large-letter-spacing;
}

.sign {
  font-family: $typography-data-large-units-font-family;
  font-weight: $typography-data-large-units-font-weight;
  font-size: $typography-data-large-units-font-size;
  line-height: $typography-data-large-units-line-height;
  letter-spacing: $typography-data-large-units-letter-spacing;
}
```

`ANumber.tsx`
```tsx
export const ANumber:React.FC<Props> = ({ number }) => {
  return (
    <div className={styles.container}>
      <Heading
        tag="span"
        variant="heading-1" // data-large
        classNameAndIHaveSpokenToDST={styles.number}
      >
        {percentage}
      </Heading>
      <Heading
        tag="span"
        variant="heading-2" // data-unit-large
        classNameAndIHaveSpokenToDST={styles.sign}
      >
        %
      </Heading>
    </div>
  )
}
```
